import os

MODEL_ID = "onnx-community/Voxtral-Mini-4B-Realtime-2602-ONNX"
SAMPLE_RATE = 16000
N_FFT = 400
HOP_LENGTH = 160
WIN_LENGTH = 400
N_MELS = 128
GLOBAL_LOG_MEL_MAX = 1.5
AUDIO_LENGTH_PER_TOK = 8
DEFAULT_NUM_DELAY_TOKENS = 6
DOWNSAMPLE_FACTOR = 4
MAX_NEW_TOKENS = 4096

MODELS_DIR = os.environ.get("MODELS_DIR", "/models")
STT_THREADS = int(os.environ.get("STT_THREADS", "4"))
VARIANT = os.environ.get("VARIANT", "q4")
