name: CI

on:
  push:
    branches:
      - "vertexai"
  pull_request:
    branches:
      - "vertexai"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Dummy success step
        run: echo "CI check passed"
